apiVersion: v1
kind: Namespace
metadata:
  name: store-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-project
  namespace: store-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-project
  template:
    metadata:
      labels:
        app: store-project
    spec:
      containers:
        - name: store-project
          image: mrajkumar21/store:v1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0  # Run as root user
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: store-project-service
  namespace: store-project
spec:
  selector:
    app: store-project
  ports:
    - protocol: TCP
      port: 8080  # Port on the service
      targetPort: 8080  # Port on the pods
  type: ClusterIP